<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>try~catch~finally 문 사용 예</title>
  </head>
  <body>
    <h3>0~9숫자가 입력되었는지 체크하기</h3>
    <input id="input1" type="text" /><span id="show"></span><br />
    <button onclick="checkInput()">확인</button>

    <script>
      function checkInput() {
        let input_elem = document.getElementById("input1");
        let a = input_elem.value;
        document.getElementById("show").innerHTML = "";
        try {
          if (a == "") throw "비어 있습니다.";
          if (isNaN(a)) throw "숫자가 아닙니다.";
          a = Number(a);
          if (a < 0 || a > 9) throw "0~9 사이 숫자가 아닙니다.";
        } catch (err) {
          document.getElementById("show").innerHTML = "오류: " + err;
        } finally {
          input_elem.value = ""; // 입력창에 입력된 값을 Null("")로 초기화한다.
        }
      }

      // try~catch~finally 문에서는 finally는 try~ 블럭의 결과와 상관없이 무조건 실행된다.
      // 에러가 발생하는지 여부와 상관없이 실행된다.
    </script>
  </body>
</html>
